services:
  myapp:
    image: openjdk:17
    environment:
      - SPRING_APPLICATION_NAME=lab9Container
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/myappdb
      - SPRING_DATASOURCE_USERNAME=mca043
      - SPRING_DATASOURCE_PASSWORD=mca043
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ["java","-jar","/app/demo1-0.0.1-SNAPSHOT.jar"]
    volumes:
      - .:/app
  db:
   image: mysql
   environment:
     - MYSQL_DATABASE=myappdb
     - MYSQL_USER=mca043
     - MYSQL_PASSWORD=mca043
     - MYSQL_ROOT_PASSWORD=root
   ports:
     - "3306:3307"
